fix: Address equality for exported ifunc symbols (#1452)
This is the final patch set in a series of changes addressing address
equivalence for ifunc functions. When running the tests in
`ifunc-export.c` with the current `main` implementation, the dynamic
linker reports a circular dependency at runtime:
```
---- integration_test::program_name_97___ifunc_export_c__ stdout ----
Error: Failed to run program. Binary `/home/lapla/repos/wild/wild/tests/build/ifunc-export.c/ifunc-export.c-default-host.wild`. Relink with:
WILD_WRITE_LAYOUT=1 WILD_WRITE_TRACE=1 OUT=/home/lapla/repos/wild/wild/tests/build/ifunc-export.c/ifunc-export.c-default-host.wild /home/lapla/repos/wild/wild/tests/build/ifunc-export.c/ifunc-export.c-default-host.save/run-with cargo run --bin wild --
  Caused by:
    Binary exited with unexpected exit code 127: /home/lapla/repos/wild/wild/tests/build/ifunc-export.c/ifunc-export.c-default-host.wild: IFUNC symbol 'foo' referenced in '/home/lapla/repos/wild/wild/tests/build/ifunc-export.c/ifunc-export-1.default-host-5051386a5e303a08.wild.so' is defined in the executable and creates an unsatisfiable circular dependency.
```

Even when an ifunc symbol is exported from a binary and referenced by a
dynamic library, Wild has historically resolved this symbol with the
`STT_GNU_IFUNC` type and kept the resolution address. In such cases, the
actual processing required should be as follows:
1. Change the symbol value to the PLT stub address
2. Change the symbol type from `STT_GNU_IFUNC` to `STT_FUNC`
3. Change the symbol's section to the PLT section