Identify kind of archive members instead of copying from their parent
It also means when we encounter an archive with LTO objects, we correctly reject them.
Previously:
```
Error: Failed to parse object file `librustc_codegen_llvm-6a14a3ed70dffd38.rlib @ ef10e86dc40538c1-PassWrapper.o`

Caused by:
    Unsupported ELF header
```
Now:
```
Error: Failed to parse archive `librustc_codegen_llvm-6a14a3ed70dffd38.rlib @ ef10e86dc40538c1-PassWrapper.o`

Caused by:
    LLVM IR (LTO mode) is not supported yet
```