tests: drop parse_bool and provide more context
Newly reported:
```
  Error: Failed to process test directive wild/tests/sources/elf/compressed-debug/compressed-debug.c:12
    Caused by:
      problematic directive line: 'RequiresZstdCompression:dog'
      provided string was not `true` or `false`
```

I fell it's much better as we provide enough information about the wrong directive.